.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

**Summary:**
This PR adds issue templates.
Implement
- the `ISSUE_TEMPLATE` folder
Issues have now templates and you can choose the one you want

feat: adds issues templates

---

.github/workflows/verify-source-url.yml

Quick fix to verify-source-url.yml workflow

Modifies verify-source-url.yml workflow

---

scripts/verify_source_url.py

Quick fix for verify-source-url.py

Modifies verify-source-url.py

---

.github/workflows/export_to_csv.yml
.github/workflows/integration_tests.yml
.github/workflows/python_style_checker.yml
.github/workflows/unit_tests.yml

**Summary:**
Fixes #33: Add workflow to verify PEP8 compliancy (code styling)
This PR adds the workflow to check the Python code styling before merging.
Implement:
- `python_style_checker`, the workflow verifying the code style is compliant with [PEP8](https://www.python.org/dev/peps/pep-0008/) using [Flake8](https://flake8.pycqa.org/en/latest/).
Changes:
- The `flake8` dependency was removed from the other workflows
The workflow succeeds if the code in a PR is compliant with PEP8, fails otherwise.

feat: Add Python style checker workflow

---

.github/semantic.yml

**Summary:**
This enables a bot to enforce semantic PR titles, same as static validator - see https://github.com/MobilityData/gtfs-validator/pull/497 and https://github.com/MobilityData/gtfs-validator/blob/master/.github/semantic.yml.
Same PR as [here](https://github.com/MobilityData/gtfs-realtime-validator/pull/91)
**Expected behaviour:** 
Semantic bot should run on pull requests

ci: Adds semantic validation for PR titles

---

CONTRIBUTING.md
README.md

Updating any reference of the Mobility Catalogs to be the Mobility Database Catalogs

docs: Update Mobility Catalogs reference

---

.github/workflows/export_to_csv.yml
CONTRIBUTING.md
README.md
catalogs/sources/gtfs/realtime/ca-ontario-barrie-transit-gtfs-rt-4.json
catalogs/sources/gtfs/realtime/ca-ontario-barrie-transit-gtfs_rt-4.json
catalogs/sources/gtfs/schedule/ca-ontario-barrie-transit-gtfs-3.json
schemas/gtfs_realtime_source_schema.json
schemas/gtfs_schedule_source_schema.json
tests/test_integration.py
tools/constants.py
tools/helpers.py
tools/operations.py
tools/representations.py
tools/tests/test_helpers.py
tools/tests/test_operations.py
tools/tests/test_representations.py

**Summary:**
Fixes #47: Add Realtime operations
Fixes #35: Add tests for tools.operations
This PR implements the GTFS Realtime operations. It implements `tools.representations` to easily manipulate the catalogs and to provide lightweight but efficient operating functions.
Implements:
- `tools.representations` including the superclasses `Catalog` and `Source` , and the implemented classes `SourcesCatalog`, `GtfsScheduleSourcesCatalog`, `GtfsRealtimeSourcesCatalog`, `GtfsScheduleSource` and `GtfsRealtimeSource`.
- `test_representations.py` and `test_operations.py`
- Barrie Transit's GTFS Schedule and GTFS Realtime sources are added to display the static_reference relationship between a GTFS Schedule and a GTFS Realtime source. 
Changes:
- `README.md` and `CONTRIBUTING.md` have been updated …

feat: Add GTFS Realtime operations

---

tools/helpers.py

**Summary:**
Fixes #75: `tools.helpers.is_readable` had a syntax problem.
This PR fixes the syntax problem in `tools.helpers.is_readable`.
Changes:
- `helpers.py` is updated to fix the syntax.
The correct exception message is returned and not the exception message related to the syntax problem

fix: `is_readable` syntax problem

---

.github/workflows/export_to_csv.yml

**Summary:**
Fixes #83: Change null behavior for location so it's blank, not "unknown"
This PR updates the null behaviour for `municipality` and `subdivision_name` in the CSV so that their respective cells appear as blank and not `unknown`.
Changes:
- `export_to_csv.yml` to update the null behavior.
The null values for `municipality` and `subdivision_name` in the exported CSV appear as blank.

feat: Change null behavior for location

---

catalogs/sources/gtfs/schedule/de-baden-wurttemberg-deutsche-bahn-s-bahn-stuttgart-gtfs-775.json
catalogs/sources/gtfs/schedule/fi-keski-suomi-jyvaskyla-gtfs-867.json
catalogs/sources/gtfs/schedule/fi-pohjois-pohjanmaa-oulun-joukkoliikenne-gtfs-869.json
catalogs/sources/gtfs/schedule/us-colorado-town-of-estes-park-gtfs-177.json
catalogs/sources/gtfs/schedule/us-massachusetts-cape-code-regional-transportation-authority-cape-cod-rta-gtfs-645.json
catalogs/sources/gtfs/schedule/us-new-jersey-new-jersey-transit-nj-transit-gtfs-508.json
catalogs/sources/gtfs/schedule/us-new-jersey-new-jersey-transit-nj-transit-gtfs-509.json
catalogs/sources/gtfs/schedule/us-new-york-mta-long-island-rail-road-gtfs-507.json
catalogs/sources/gtfs/schedule/us-new-york-mta-new-york-city-transit-gtfs-512.json
catalogs/sources/gtfs/schedule/us-new-york-mta-new-york-city-transit-mta-gtfs-510.json
catalogs/sources/gtfs/schedule/us-new-york-mta-new-york-city-transit-mta-gtfs-511.json
catalogs/sources/gtfs/schedule/us-new-york-mta-new-york-city-transit-mta-gtfs-513.json
catalogs/sources/gtfs/schedule/us-new-york-mta-new-york-city-transit-mta-gtfs-514.json
catalogs/sources/gtfs/schedule/us-new-york-mta-new-york-city-transit-mta-gtfs-516.json
catalogs/sources/gtfs/schedule/us-new-york-mta-new-york-city-transit-mta-gtfs-520.json
catalogs/sources/gtfs/schedule/us-oregon-cherriots-gtfs-128.json
catalogs/sources/gtfs/schedule/us-tennessee-chattanooga-area-regional-transportation-authority-carta-gtfs-359.json
catalogs/sources/gtfs/schedule/us-texas-gulf-coast-center-gtfs-625.json

**Summary:**
Fixes #71: First data import
This PR updates some sources of the initial data import for the GTFS Schedule sources in the catalogs.
Changes:
- 18 sources are updated in the GTFS Schedule Sources catalog.
Same as before but with updated sources.

feat: Updates sources from the initial data import [SOURCES]

---

catalogs/sources/gtfs/schedule/de-germany-verkehrsverbund-rhein-ruhr-gtfs-785.json
catalogs/sources/gtfs/schedule/de-unknown-karlsruher-verkehrsverbundes-gtfs-1225.json
catalogs/sources/gtfs/schedule/fr-paris-ile-de-france-mobilite-gtfs-1026.json
catalogs/sources/gtfs/schedule/it-sardegna-arst-spa-trasporti-regionali-della-sardegna-gtfs-895.json
catalogs/sources/gtfs/schedule/it-sardegna-collegamenti-marittimi-grandi-navi-veloci-gtfs-1265.json
catalogs/sources/gtfs/schedule/us-biscay-la-burundesa-sa-gtfs-1316.json
catalogs/sources/gtfs/schedule/us-mississipi-jtran-gtfs-155.json

This includes updates to subdivisions and country codes that were previously incorrect, including a typo flagged by Saipraneeth Devunuri via Slack. (Thank you!)

fix: Typos fixes [SOURCES]

---

catalogs/sources/gtfs/schedule/es-andalucia-metro-de-malaga-gtfs-1017.json

Based on Google Form submission.

fix: Metro de Málaga download URL change [SOURCES]

---

catalogs/sources/gtfs/schedule/fr-auvergne-rhone-alpes-ondea-compagnie-de-transport-du-lac-du-bourget-ctlb-gtfs-600.json
catalogs/sources/gtfs/schedule/fr-nouvelle-aquitaine-stga-reseau-mobius-gtfs-837.json

Two minor changes to remove the "---" in filenames.

fix: Fixes filenames from the source replacement PR

---

catalogs/sources/gtfs/schedule/cl-region-metropolitana-de-santiago-santiago-dptm-gtfs-987.json

Update `cl-region-metropolitana-de-santiago-santiago-dptm-gtfs-987.json` based on Google Form submission.

feat: Update GTFS Schedule source for Santiago DTPM [Sources]

---

catalogs/sources/gtfs/schedule/es-andalucia-metro-de-malaga-gtfs-1017.json

URL update of source 1017 based on May 11, 2022 Google form submission from Metro de Málaga.

feat: metro de malaga URL update [SOURCES]

---

catalogs/sources/gtfs/schedule/ae-abu-dhabi-emirate-department-of-municipalities-and-transport-gtfs-1329.json

New source contributed by Department of Municipalities and Transport, Abu Dhabi, UAE.

feat: abu dhabi source addition [SOURCES]

---

catalogs/sources/gtfs/schedule/fr-unknown-sncf-gtfs-1782.json
catalogs/sources/gtfs/schedule/fr-unknown-sncf-gtfs-1783.json
catalogs/sources/gtfs/schedule/fr-unknown-ter-sncf-gtfs-1205.json
catalogs/sources/gtfs/schedule/us-maryland-towson-loop-gtfs-1784.json

Adding GTFS schedule sources from SNCF and Towson Loop (Passio Technologies).

feat: Source changes June 20 [SOURCES]

---

catalogs/sources/gtfs/realtime/us-maryland-towson-loop-gtfs-rt-s-a-1786.json
catalogs/sources/gtfs/realtime/us-maryland-towson-loop-gtfs-rt-t-u-1785.json
catalogs/sources/gtfs/realtime/us-maryland-towson-loop-gtfs-rt-v-p-1787.json

Adding the service alerts, vehicle positions, and trip update source for Towson Loop submitted by Passio Technologies.

feat: adding Towson Loop realtime sources

---

catalogs/sources/gtfs/schedule/ca-new-brunswick-miramichi-transit-gtfs-1806.json
catalogs/sources/gtfs/schedule/us-florida-sunrail-gtfs-626.json
catalogs/sources/gtfs/schedule/us-north-carolina-charlotte-area-transit-system-cats-gtfs-640.json

Source additions based on contributions to the Google Form:
- Miramichi Transit
Status updates: 
- Sunrail 
- CATS

fix: updates july 28 [SOURCES]

---

.github/workflows/direct_download_urls_test_for_sources.yml

fix: Fix API secrets issue blocking fork PRs take 2

---

catalogs/sources/gtfs/schedule/us-california-fresno-county-rural-transit-agency-fcrta-gtfs-85.json

Updating to current GTFS feed: https://rapid.nationalrtap.org/GTFSFileManagement/UserUploadFiles/7869/google_transit.zip
Hosted on FCRTA's Website: https://www.ruraltransit.org/transportation-guide/park-and-ride-2
[google_transit.zip](https://github.com/MobilityData/mobility-database-catalogs/files/9263826/google_transit.zip)
/

Update us-california-fresno-county-rural-transit-agency-fcrta-gtfs-85.json [SOURCES]

---

.github/config.yml

Adding a welcome bot for new PRs, merging PRs, and new issues.

feat: add welcome messages

---

catalogs/sources/gtfs/schedule/hu-unknown-volanbusz-gtfs-1836.json

Volánbusz feed from feed update form

feat: volanbusz feed addition [SOURCES]

---

catalogs/sources/gtfs/realtime/fr-normandie-cotentin-cap-cotentin-gtfs-rt-vp-sa-tu-1841.json
catalogs/sources/gtfs/schedule/fr-bretagne-breizhgo-gtfs-1837.json
catalogs/sources/gtfs/schedule/fr-grand-est-ouest-vosgien-neobus-gtfs-1839.json
catalogs/sources/gtfs/schedule/fr-normandie-cotentin-cap-cotentin-gtfs-1840.json
catalogs/sources/gtfs/schedule/fr-normandie-semo-gtfs-1838.json
catalogs/sources/gtfs/schedule/hu-unknown-volanbusz-gtfs-1836.json

feat: France feed updates [SOURCES]

---

catalogs/sources/gtfs/realtime/us-california-sfmta-gtfs-rt-sa-1844.json
catalogs/sources/gtfs/realtime/us-california-sfmta-gtfs-rt-tu-1845.json
catalogs/sources/gtfs/realtime/us-california-sfmta-gtfs-rt-vp-1843.json
catalogs/sources/gtfs/realtime/us-washington-intercity-transit-gtfs-rt-sa-1538.json
catalogs/sources/gtfs/realtime/us-washington-intercity-transit-gtfs-rt-tu-1539.json
catalogs/sources/gtfs/realtime/us-washington-intercity-transit-gtfs-rt-vp-1537.json
catalogs/sources/gtfs/realtime/us-washington-king-county-metro-gtfs-rt-sa-1541.json
catalogs/sources/gtfs/realtime/us-washington-king-county-metro-gtfs-rt-tu-1540.json
catalogs/sources/gtfs/realtime/us-washington-king-county-metro-gtfs-rt-vp-1542.json
catalogs/sources/gtfs/schedule/us-california-ucsc-transportation-and-parking-services-gtfs-1842.json
catalogs/sources/gtfs/schedule/us-washington-intercity-transit-gtfs-266.json
catalogs/sources/gtfs/schedule/us-washington-sound-transit-metro-transit-city-of-seattle-king-county-metro-gtfs-267.json

Updating and adding feeds from Google form submissions and email updates:
- SFMTA
- UCSC Transportation Services
- Intercity Transit
- King County Transit

feat: update feeds [SOURCES]

---

catalogs/sources/gtfs/realtime/us-district-of-columbia-washington-metropolitan-area-transit-authority-wmata-gtfs-rt-sa-1848.json
catalogs/sources/gtfs/realtime/us-district-of-columbia-washington-metropolitan-area-transit-authority-wmata-gtfs-rt-sa-1851.json
catalogs/sources/gtfs/realtime/us-district-of-columbia-washington-metropolitan-area-transit-authority-wmata-gtfs-rt-tu-1849.json
catalogs/sources/gtfs/realtime/us-district-of-columbia-washington-metropolitan-area-transit-authority-wmata-gtfs-rt-tu-1852.json
catalogs/sources/gtfs/realtime/us-district-of-columbia-washington-metropolitan-area-transit-authority-wmata-gtfs-rt-vp-1850.json
catalogs/sources/gtfs/realtime/us-district-of-columbia-washington-metropolitan-area-transit-authority-wmata-gtfs-rt-vp-1853.json
catalogs/sources/gtfs/schedule/es-barcelona-amb-gtfs-1101.json
catalogs/sources/gtfs/schedule/us-district-of-columbia-washington-wmata-gtfs-1846.json
catalogs/sources/gtfs/schedule/us-district-of-columbia-washington-wmata-gtfs-1847.json

Feeds for WMATA as requested by ITDP.

feat: wmata feeds [SOURCES]

---

catalogs/sources/gtfs/realtime/no-go-ahead-gtfs-rt-vp-1797.json
catalogs/sources/gtfs/realtime/no-ruter-gtfs-rt-sa-1799.json
catalogs/sources/gtfs/realtime/no-ruter-gtfs-rt-tu-1798.json
catalogs/sources/gtfs/realtime/no-vy-buss-gtfs-rt-sa-1802.json
catalogs/sources/gtfs/realtime/no-vy-buss-gtfs-rt-tu-1800.json
catalogs/sources/gtfs/realtime/no-vy-buss-gtfs-rt-vp-1801.json
catalogs/sources/gtfs/realtime/no-vy-express-gtfs-rt-sa-1804.json
catalogs/sources/gtfs/realtime/no-vy-express-gtfs-rt-tu-1805.json
catalogs/sources/gtfs/realtime/no-vy-express-gtfs-rt-vp-1803.json

Update Norway GTFS-RT feeds to include static reference.

feat: update norway gtfs-rt feeds

---

catalogs/sources/gtfs/schedule/es-barcelona-amb-gtfs-1101.json

Fix link to 1101 to point to new file.

fix: AMB link

---

catalogs/sources/gtfs/schedule/us-california-auburn-transit-gtfs-217.json
catalogs/sources/gtfs/schedule/us-california-avalon-transit-gtfs-12.json
catalogs/sources/gtfs/schedule/us-california-beaumont-gtfs-106.json
catalogs/sources/gtfs/schedule/us-california-blossom-express-gtfs-236.json
catalogs/sources/gtfs/schedule/us-california-camarillo-area-transit-gtfs-297.json
catalogs/sources/gtfs/schedule/us-california-city-of-banning-transit-gtfs-220.json
catalogs/sources/gtfs/schedule/us-california-city-of-madera-gtfs-91.json
catalogs/sources/gtfs/schedule/us-california-city-of-tracy-tracer-gtfs-877.json
catalogs/sources/gtfs/schedule/us-california-city-of-wasco-gtfs-1788.json
catalogs/sources/gtfs/schedule/us-california-clovis-transit-gtfs-89.json
catalogs/sources/gtfs/schedule/us-california-delano-area-rapid-transit-gtfs-320.json
catalogs/sources/gtfs/schedule/us-california-glenn-transit-service-gtfs-835.json
catalogs/sources/gtfs/schedule/us-california-guadalupe-flyer-gtfs-617.json
catalogs/sources/gtfs/schedule/us-california-lassen-rural-bus-lrb-gtfs-118.json
catalogs/sources/gtfs/schedule/us-california-mission-bay-transportation-management-association-tma-gtfs-51.json
catalogs/sources/gtfs/schedule/us-california-redding-area-bus-authority-raba-gtfs-114.json
catalogs/sources/gtfs/schedule/us-california-spirit-bus-gtfs-39.json
catalogs/sources/gtfs/schedule/us-california-tehama-rural-area-express-trax-susanville-indian-rancheria-public-transportation-program-gtfs-116.json
catalogs/sources/gtfs/schedule/us-california-trinity-transit-gtfs-115.json
catalogs/sources/gtfs/schedule/us-california-yosemite-area-regional-transportation-system-yarts-gtfs-88.json

Add the "fares-v2" features tag to several feeds.

Tag Cal-ITP (Trillium feeds) Fares v2 [SOURCES]

---

catalogs/sources/gtfs/schedule/be-antwerpen-dewaterbus-gtfs-1860.json
catalogs/sources/gtfs/schedule/be-bruxelles-capitale-societe-des-transports-intercommunaux-de-bruxellesmaatschappij-voor-het-intercommunaal-vervoer-te-brussel-stibmivb-gtfs-1088.json
catalogs/sources/gtfs/schedule/be-hainaut-tec-gtfs-1868.json
catalogs/sources/gtfs/schedule/be-unknown-sncb-gtfs-1859.json
catalogs/sources/gtfs/schedule/be-unknown-societe-nationale-des-chemins-de-fer-belges-nmbs-sncb-gtfs-1857.json
catalogs/sources/gtfs/schedule/be-unknown-stib-mivb-gtfs-1857.json
catalogs/sources/gtfs/schedule/be-wallonne-tec-gtfs-1868.json
catalogs/sources/gtfs/schedule/br-ceara-etufor-gtfs-1863.json
catalogs/sources/gtfs/schedule/br-rio-de-janeiro-city-transport-secretary-of-rio-de-janeiro-gtfs-1791.json
catalogs/sources/gtfs/schedule/br-rio-grande-do-sul-empresa-publica-de-transportes-e-circulacao-eptc-gtfs-7.json
catalogs/sources/gtfs/schedule/ca-ontario-belleville-transit-gtfs-1858.json
catalogs/sources/gtfs/schedule/cl-la-araucania-temuco-gtfs-1864.json
catalogs/sources/gtfs/schedule/cl-maule-talca-gtfs-1866.json
catalogs/sources/gtfs/schedule/cl-o'higgins-rancagua-talca-gtfs-1865.json
catalogs/sources/gtfs/schedule/de-baden-wurttemberg-verkehrsverbund-rhein-neckar-gtfs-1173.json
catalogs/sources/gtfs/schedule/es-catalunya-ferrocarrils-de-la-generalitat-de-catalunya-gtfs-1856.json
catalogs/sources/gtfs/schedule/fr-auvergne-rhone-alpes-mobilites-m---tougo-gtfs-1855.json
catalogs/sources/gtfs/schedule/fr-auvergne-rhone-alpes-mobilites-m---transports-du-pays-voironnais-gtfs-1854.json
catalogs/sources/gtfs/schedule/fr-auvergne-rhone-alpes-syndicat-mixte-des-mobilites-de-laire-grenobloise-gtfs-641.json
catalogs/sources/gtfs/schedule/fr-auvergne-rhone-alpes-transports-de-lagglomeration-grenobloise-tag-gtfs-1055.json
catalogs/sources/gtfs/schedule/in-kerala-kochi-metro-gtfs-1209.json
catalogs/sources/gtfs/schedule/us-kansas-salina-gtfs-1867.json
catalogs/sources/gtfs/schedule/us-north-carolina-wave-transit-gtfs-1861.json
catalogs/sources/gtfs/schedule/us-north-carolina-wave-transit-gtfs-1862.json

Feed updates and additions. Feed contributions made by 
- ITDP
- gtfs.be
- Eloi Torrents
- SMMAG

feat: feed updates from ITDP, gtfs.be, Eloi Torrents and SMMAG

---

README.md

Updating contributing section so we commit to responding to PRs and form contributions within a week.

feat: update contributing section

---

catalogs/sources/gtfs/schedule/ca-british-columbia-rider-express-gtfs-1871.json

Adding Rider Express feed from British Columbia, as contributed by Ticpoi, the data producer.

feat: Add Rider Express feed [SOURCES]

---

catalogs/sources/gtfs/schedule/us-california-clean-air-express-gtfs-1872.json

Add development feed for Clean Air Express with latest changes to fare_media from https://github.com/google/transit/pull/355

Add Clean Air Express Fares-v2 [SOURCES]

---

catalogs/sources/gtfs/schedule/pt-lisboa-carris-metropolitana-gtfs-1900.json

Feed shared by Carris Metropolitana.

feat: Carris Metropolitana feed [SOURCES]

---

catalogs/sources/gtfs/schedule/us-washington-metro-transit-gtfs-1080.json

Updated Puget Sound Consolidated feed URL, contributed by Michael Kirk

update puget sound consolidated [SOURCES]

---

catalogs/sources/gtfs/schedule/hu-szeged-dakk-zrt-gtfs-887.json
catalogs/sources/gtfs/schedule/us-indiana-citybus-of-greater-lafayette-indiana-citybus-gtfs-391.json

Feed updates from Randy A, CityBus and Kovács Áron.

feat: lafayette and szeged updates [SOURCES]

---

catalogs/sources/gtfs/schedule/us-utah-cache-valley-gtfs-1906.json

Anonymous contribution from https://database.mobilitydata.org/update-a-data-source

feat: cache valley gtfs schedule [SOURCES]

---

catalogs/sources/gtfs/schedule/pl-podlaskie-bialostocka-komunikacja-miejska-gtfs-1907.json

Hey. This is my first contrib. Hope everything is ok. 
I created the file using the `add_gtfs_schedule_source` python package as the README/CONTRIBUTING.md instructed

feat: add Białystok GTFS Source [SOURCES]

---

catalogs/sources/gtfs/schedule/pl-malopolskie-koleje-malopolskie-gtfs-1908.json

Submitted by Koleje Małopolskie.

feat: koleje malopolskie feed [SOURCES]

---

catalogs/sources/gtfs/schedule/do-santiago-ayuntamiento-del-municipio-de-santiago-gtfs-1914.json
catalogs/sources/gtfs/schedule/es-andalucia-transporte-publicos-de-andalucia-gtfs-1913.json
catalogs/sources/gtfs/schedule/es-santiago-gtfs-1914.json

Feeds contributed by Transporte Públicos de Andalucía and the Institute for Transportation & Development Policy.

feat: Santiago and Andalucía feeds

---

catalogs/sources/gtfs/schedule/us-california-long-beach-transit-lbt-gtfs-1198.json

Update of Long Beach Transit's feed, shared by Long Beach Transit Service Planning.

fix: long beach transit update [SOURCES]

---

catalogs/sources/gtfs/realtime/us-washington-c-tran-gtfs-rt-tu-1922.json
catalogs/sources/gtfs/realtime/us-washington-c-tran-gtfs-rt-vp-1921.json
catalogs/sources/gtfs/schedule/us-south-carolina-greenville-transit-authority-greenlink-gtfs-1923.json
catalogs/sources/gtfs/schedule/us-washington-link-transit-gtfs-275.json

Feed contributions from 
- C-TRAN
- Greenville Transit Authority
- WSDOT for Link Transit

feat: Jul 4 feeds [SOURCES]

---

catalogs/sources/gtfs/schedule/hk-unknown-hong-kong-government-transport-department-gtfs-1924.json
catalogs/sources/gtfs/schedule/mx-jalisco-secretaria-de-movilidad-del-estado-de-jalisco-gtfs-1925.json
catalogs/sources/gtfs/schedule/mx-jalisco-secretaria-de-movilidad-del-estado-de-jalisco-gtfs-1926.json

Contribution from SITEUR and anonymous.

feat: Jul 13 update from Hong Kong and Jalisco [SOURCES]

---

catalogs/sources/gtfs/realtime/unknown-unknown-motionbuscard-gtfs-rt-vp-tu-1920.json

source: https://www.motionbuscard.org.cy/opendata

fix: Adjust motionbus rt url

---

CONTRIBUTING.md

https://database.mobilitydata.org/update-a-data-source doesn’t work (404 error) and I think it should be https://database.mobilitydata.org/add-a-feed now.

docs: Update add feed form URL

---

catalogs/sources/gtfs/schedule/br-rio-de-janeiro-city-transport-secretary-of-rio-de-janeiro-gtfs-1791.json
catalogs/sources/gtfs/schedule/cd-kinshasa-esprit-de-mort-gtfs-1963.json
catalogs/sources/gtfs/schedule/cd-kinshasa-esprit-de-mort-gtfs-1964.json
catalogs/sources/gtfs/schedule/et-addis-ababa-sheger-city-bus-gtfs-1959.json
catalogs/sources/gtfs/schedule/rw-kigali-kigali-bus-services-gtfs-1961.json
catalogs/sources/gtfs/schedule/rw-kigali-kigali-bus-services-gtfs-1962.json
catalogs/sources/gtfs/schedule/us-new-hampshire-dartmouth-college-gtfs-1958.json
catalogs/sources/gtfs/schedule/za-stellenbosch-esprit-de-mort-gtfs-1965.json
catalogs/sources/gtfs/schedule/zw-harare-harare-kombis-gtfs-1960.json

Contributions from 
- Digital Transport for Africa
- Rio de Janeiro City Hall
- Dartmouth College

Update from Digital Transport for Africa, Rio de Janeiro City Hall, Dartmouth College [SOURCES]

---

catalogs/sources/gtfs/realtime/us-california-redding-area-bus-authority-gtfs-rt-sa-1485.json
catalogs/sources/gtfs/realtime/us-california-redding-area-bus-authority-gtfs-rt-tu-1487.json
catalogs/sources/gtfs/realtime/us-california-redding-area-bus-authority-gtfs-rt-vp-1486.json
catalogs/sources/gtfs/schedule/us-california-redding-area-bus-authority-raba-gtfs-114.json
catalogs/sources/gtfs/schedule/us-california-redding-area-bus-authority-raba-gtfs-1972.json
catalogs/sources/gtfs/schedule/us-north-carolina-link-transit-gtfs-1971.json

Official contribution from John Andoh - changes to RABA's feed and addition of Link Transit's feed.

Redding Area Bus Authority and Link Transit Feeds [SOURCES]

---

catalogs/sources/gtfs/schedule/us-california-redding-area-bus-authority-raba-gtfs-114.json

Fixing syntax of redirect so the CSV runs

Update us-california-redding-area-bus-authority-raba-gtfs-114.json [SOURCES]

---

.github/workflows/add_new_or_updated_feeds.yml

Part of [#16](https://github.com/MobilityData/mobility-feed-api/issues/16)
**Summary:**
Added a sent trigger to the `mobility-feed-api` once the catalog's CSV file has been updated

feat: adding trigger catalog -> api

---

.github/workflows/add_new_or_updated_feeds.yml
scripts/process_csv_in_github_action.swift

The issue: the swift script outputs this:
```
add_gtfs_schedule_source(provider="Mountain Line Transit", country_code="US", direct_download_url="http://mountainline.syncromatics.com/gtfs", authentication_type=0, authentication_info_url="", api_key_parameter_name="", subdivision_name="Arizona", municipality="Flagstaff", license_url="INVALID_OR_NO_URL_PROVIDED", name="", status="", features="")
```
But what the python script receives is this:
```
add_gtfs_schedule_source(provider="Mountain Line Transit", country_code="US", direct_download_url="http://mountainline.syncromatics.com/gtfs", authentication_type=0, authentication_info_url=", api_key_parameter_name=", subdivision_name="Arizona", municipality="Flagstaff", license_url="INVALID_OR_NO_URL_PROVIDED", name=", status=", features=")
``` …

Possible fix for missing double quotes.

---

.github/workflows/add_new_or_updated_feeds.yml

This is a first attempt, doc is limited a bit. It will send a notification to the internal-public-transit channel when a push was done so Emma can be made aware.

feat: added notification to slack channel when push

---

catalogs/sources/gtfs/schedule/pe--aeroexpreso-gtfs-1985.json
catalogs/sources/gtfs/schedule/pe-aeroexpreso-gtfs-1985.json
catalogs/sources/gtfs/schedule/ro-vrancea-consiliul-judetean-vrancea-gtfs-1984.json

Contributions from 
- Consiliul Judetean Vrancea
- Aeroexpreso

Automated commit — New/Updated feed: 02-07 [SOURCES]

---

scripts/process_csv_in_github_action.swift

feat: added redirect & feed_contact_email

---

scripts/process_csv_in_github_action.swift

Was checking if the value was empty, turns out the count of chars in the var was 2, so I changed the check to .count < 4.

Fix: improved checks for URL

---

scripts/process_csv_in_github_action.swift

Force conversion of `mdb_source_id` to Int, remove `direct_download_url`

Force conversion of `mdb_source_id` to Int, remove `direct_download_url`

---

README.md

Update README.md with schema changes

---

.github/workflows/add_new_or_updated_feeds.yml

Used a different Github action, improved the message by adding the URL to the newly created branch.

fix: improve the Slack notification

---

catalogs/sources/gtfs/schedule/it-brindisi-stp-brindisi-gtfs-2020.json
catalogs/sources/gtfs/schedule/it-brindisi-stp-brindisi-gtfs-2021.json
catalogs/sources/gtfs/schedule/it-brindisi-stp-brindisi-gtfs-2022.json
catalogs/sources/gtfs/schedule/it-brindisi-stp-brindisi-gtfs-2023.json
catalogs/sources/gtfs/schedule/lv-jurmala-jurmalas-autobusu-satiksme-gtfs-2018.json
catalogs/sources/gtfs/schedule/lv-liepaja-liepajas-sabiedriskais-transports-gtfs-2016.json
catalogs/sources/gtfs/schedule/lv-rezekne-rezeknes-satiksme-gtfs-2017.json
catalogs/sources/gtfs/schedule/lv-unknown-pasazieru-vilciens-gtfs-2015.json
catalogs/sources/gtfs/schedule/us-illinois-rockford-mass-transit-district-gtfs-2019.json

Contributions for 
- STP Brindisi
- Rockford Mass Transit District 
- Jūrmalas autobusu satiksme
- Rēzeknes satiksme
- Liepājas sabiedriskais transports
- Pasažieru Vilciens

Automated commit — New/Updated feed: March 4, 2024 [SOURCES]

---

scripts/process_csv_in_github_action.swift

Did a quick fix for now, to save time.

Removed the condition to process only feeds with today's date.

---

.github/workflows/add_new_or_updated_feeds.yml

The channel has changed for this notification:
* Changed the channel ID
* Upped the version for 1Password action and the Slack channel action
* Try to fix the missing run number when the action fails by using a env var.

fix-Changed Slack Channel

---

catalogs/sources/gtfs/schedule/us-washington-ben-franklin-transit-gtfs-2024.json
catalogs/sources/gtfs/schedule/us-washington-ben-franklin-transit-gtfs-273.json

Ben Franklin Transit feed update as contributed by the transit agency.

Ben Franklin Transit Feed [SOURCES]

---

catalogs/sources/gtfs/schedule/us-california-mountain-view-transportation-management-association-gtfs-60.json
catalogs/sources/gtfs/schedule/us-california-mountain-view-transportation-management-association-mvgo-gtfs-2025.json

Update of Mountain View Transportation Management Association (MVgo) feed from their team.

MVgo update [SOURCES]

---

catalogs/sources/gtfs/schedule/us-california-relaxsan-gtfs-2026.json

reLAXsan feed contributed by @antrim

reLAXsan new feed [SOURCES]

---

.github/workflows/export_to_csv.yml

fix: Corrected a problem where the csv file was not uploaded after a push to main

---

scripts/process_csv_in_github_action.swift

... it fails the Github action tests.

Fix-Removed default licence URL string

---

.github/workflows/store_latest_datasets_cronjob.yml

**Summary:**
- Updated the storage frequency for new datasets to align with the `mobility-feeds-api` cadence.
Closes https://github.com/MobilityData/mobility-feed-api/issues/518

feat: changing schedule to every Monday and Thursday

---

scripts/process_csv_in_github_action.swift

... plus added new case for issue types:
`case isAddNewSource = "New source"`

fix: download url not captured correctly

---

scripts/process_csv_in_github_action.swift

Many changes done in multiple steps, will not affect the execution in any way.

Streamlined code & general cleanup

---

catalogs/sources/gtfs/schedule/united-states-minnesota-city-of-winona-mn---winona-transit-service-gtfs-2032.json
catalogs/sources/gtfs/schedule/usa-ca-relaxsan-gtfs-2030.json

Correcting issue with country code format from #383 to unblock https://github.com/MobilityData/mobility-feed-api/pull/562 cc @AlfredNwolisa

Fix country code for 2030 and 2032

---

catalogs/sources/gtfs/schedule/czech-prague-bean-shuttle-gtfs-2036.json
catalogs/sources/gtfs/schedule/mexico-jalisco-direccion-general-de-transporte-publico-de-puerto-vallarta-gtfs-2034.json
catalogs/sources/gtfs/schedule/mexico-oaxaca-secretaria-de-movilidad-oaxaca-gtfs-2033.json
catalogs/sources/gtfs/schedule/us-missouri-metro-st-louis-gtfs-2035.json

Add new feeds for Secretaría de Movilidad Oaxaca, Metro St. Louis, Bean Shuttle [SOURCES]

---

scripts/process_csv_in_github_action.swift

turns out the words `Feed update` are new, the script was looking for `Source update`. Added both possibilities, should work now.
Without this it defaulted to add new feed, which is not what's desired :-)

Added `Feed Update` as new issue type

---

catalogs/sources/gtfs/realtime/us-new-york-bus-gtfs-rt-sa-1628.json
catalogs/sources/gtfs/realtime/us-new-york-long-island-rail-road-gtfs-rt-sa-1625.json
catalogs/sources/gtfs/realtime/us-new-york-long-island-rail-road-gtfs-rt-vp-tu-1624.json
catalogs/sources/gtfs/realtime/us-new-york-metro-north-railroad-gtfs-rt-sa-1626.json
catalogs/sources/gtfs/realtime/us-new-york-metro-north-railroad-gtfs-rt-tu-1627.json
catalogs/sources/gtfs/realtime/us-new-york-nyc-subway-1-gtfs-rt-vp-tu-1635.json
catalogs/sources/gtfs/realtime/us-new-york-nyc-subway-ace-lines-gtfs-rt-vp-tu-1630.json
catalogs/sources/gtfs/realtime/us-new-york-nyc-subway-bdfm-lines-gtfs-rt-vp-tu-1631.json
catalogs/sources/gtfs/realtime/us-new-york-nyc-subway-g-line-gtfs-rt-vp-tu-1632.json
catalogs/sources/gtfs/realtime/us-new-york-nyc-subway-gtfs-rt-sa-1629.json
catalogs/sources/gtfs/realtime/us-new-york-nyc-subway-jz-lines-gtfs-rt-vp-tu-1633.json
catalogs/sources/gtfs/realtime/us-new-york-nyc-subway-l-train-gtfs-rt-vp-tu-1636.json
catalogs/sources/gtfs/realtime/us-new-york-nyc-subway-nqrw-lines-gtfs-rt-vp-tu-1634.json
catalogs/sources/gtfs/schedule/au-western-australia-transcollie-gtfs-1086.json
catalogs/sources/gtfs/schedule/es-unknown-alta-velocidad-larga-distancia-media-distancia-gtfs-790.json
catalogs/sources/gtfs/schedule/gb-westminster-transport-for-london-gtfs-995.json
catalogs/sources/gtfs/schedule/united-states-minnesota-city-of-winona-mn---winona-transit-service-gtfs-2032.json
catalogs/sources/gtfs/schedule/us-new-york-mta-long-island-rail-road-gtfs-507.json
catalogs/sources/gtfs/schedule/us-new-york-mta-new-york-city-transit-gtfs-512.json
catalogs/sources/gtfs/schedule/us-new-york-mta-new-york-city-transit-mta-gtfs-510.json
catalogs/sources/gtfs/schedule/us-new-york-mta-new-york-city-transit-mta-gtfs-511.json
catalogs/sources/gtfs/schedule/us-new-york-mta-new-york-city-transit-mta-gtfs-513.json
catalogs/sources/gtfs/schedule/us-new-york-mta-new-york-city-transit-mta-gtfs-514.json
catalogs/sources/gtfs/schedule/us-new-york-mta-new-york-city-transit-mta-gtfs-516.json
catalogs/sources/gtfs/schedule/us-new-york-mta-new-york-city-transit-mta-gtfs-520.json
catalogs/sources/gtfs/schedule/us-new-york-mta-new-york-city-transit-mta-gtfs-528.json
catalogs/sources/gtfs/schedule/us-wisconsin-milwaukee-county-transit-system-gtfs-1318.json

Correcting 
- Transit provider names for New York City, Spain, and Milwaukee data
- Location for Australian data

Metadata fixes [SOURCES]

---

catalogs/sources/gtfs/schedule/at-unknown-bean-shuttle-gtfs-859.json
catalogs/sources/gtfs/schedule/us-missouri-metro-st-louis-gtfs-2035.json

@emmambd this is the PR for the feed update we did last week. Fred has been able to fix it

Automated commit — Updated feed (Bean Shuttle ,Metro St. Louis)[SOURCES]

---

.github/workflows/add_new_or_updated_feeds.yml

Fix: added PR creation after commit

---

catalogs/sources/gtfs/schedule/ca-alberta-red-deer-transit-gtfs-713.json
catalogs/sources/gtfs/schedule/ca-british-columbia-fraser-valley-express-gtfs-698.json
catalogs/sources/gtfs/schedule/ca-british-columbia-translink-vancouver-gtfs-1222.json
catalogs/sources/gtfs/schedule/ca-british-columbia-translink-west-coast-express-gtfs-696.json
catalogs/sources/gtfs/schedule/us-california-santa-rosa-citybus-gtfs-73.json
catalogs/sources/gtfs/schedule/us-massachusetts-massachusetts-area-express-max-gtfs-431.json
catalogs/sources/gtfs/schedule/us-new-york-greater-glens-falls-transit-gtfs-542.json
catalogs/sources/gtfs/schedule/us-oregon-high-desert-point-gtfs-636.json
catalogs/sources/gtfs/schedule/us-oregon-hut-airport-shuttle-gtfs-635.json
catalogs/sources/gtfs/schedule/us-virginia-potomac-and-rappahannock-transportation-commission-prtc-gtfs-481.json

2024-08-02-SOURCES

---

.github/workflows/add_new_or_updated_feeds.yml

Fix files not being committed

---

catalogs/sources/gtfs/schedule/ca-quebec-societe-de-transport-de-loutaouais-gtfs-740.json

Update ca-quebec-societe-de-transport-de-loutaouais-gtfs-740.json [SOURCES]

---

catalogs/sources/gtfs/schedule/us-iowa-the-jule-gtfs-207.json
catalogs/sources/gtfs/schedule/us-iowa-the-jule-gtfs-2083.json

This pull request contains new or updated feed(s)

Automated Pull Request — New/Updated feed(s) [SOURCES]

---

CONTRIBUTING.md

Fix the broken add feed form pointing the link to the correct URL.

fix: broken add feed form link

---

.github/workflows/add_new_or_updated_feeds.yml
.github/workflows/direct_download_urls_test_for_sources.yml
.github/workflows/export_to_csv.yml
.github/workflows/integration_tests.yml
.github/workflows/python_style_checker.yml
.github/workflows/store_latest_datasets_cronjob.yml
.github/workflows/unit_tests.yml

This PR updates the deprecated GitHub actions to its latest version.

chore: update deprecated actions

---

README.md

Forgot to change one of bit.ly link to share.mobilitydata.org

---

catalogs/sources/gtfs/schedule/us-california-fairfield-and-suisun-transit-fast-transit-gtfs-76.json
catalogs/sources/gtfs/schedule/us-california-humboldt-county-gtfs-19.json
catalogs/sources/gtfs/schedule/us-california-palos-verdes-peninsula-transit-authority-pvpta-gtfs-35.json
catalogs/sources/gtfs/schedule/us-california-placer-county-transit-gtfs-77.json
catalogs/sources/gtfs/schedule/us-california-sonoma-county-transit-sct-gtfs-70.json
catalogs/sources/gtfs/schedule/us-california-south-county-transit-link-gtfs-817.json
catalogs/sources/gtfs/schedule/us-chicago-brown-county-heartland-express-gtfs-2037.json
catalogs/sources/gtfs/schedule/us-chicago-the-otter-express-gtfs-2038.json
catalogs/sources/gtfs/schedule/us-colorado-town-of-telluride-gtfs-2050.json
catalogs/sources/gtfs/schedule/us-district-of-columbia-delmarva-community-transit-gtfs-475.json
catalogs/sources/gtfs/schedule/us-florida-pinellas-suncoast-transit-authority-psta-gtfs-326.json
catalogs/sources/gtfs/schedule/us-idaho-mountain-rides-transportation-authority-mrta-gtfs-143.json
catalogs/sources/gtfs/schedule/us-kansas-wichita-transit-gtfs-185.json
catalogs/sources/gtfs/schedule/us-maryland-allegany-county-transit-gtfs-408.json
catalogs/sources/gtfs/schedule/us-maryland-ride-on-gtfs-488.json
catalogs/sources/gtfs/schedule/us-new-york-newburgh-beacon-shuttle-leperchaun-lines-gtfs-584.json
catalogs/sources/gtfs/schedule/us-new-york-north-country-express-transit-gtfs-546.json
catalogs/sources/gtfs/schedule/us-oregon-basin-transit-service-bts-gtfs-125.json
catalogs/sources/gtfs/schedule/us-oregon-cascades-east-transit-cet-gtfs-138.json
catalogs/sources/gtfs/schedule/us-oregon-lincoln-county-transit-lct-gtfs-23.json
catalogs/sources/gtfs/schedule/us-tennessee-memphis-area-transit-authoritiy-gtfs-602.json
catalogs/sources/gtfs/schedule/us-vermont-chittenden-county-transportation-authority-ccta-gtfs-629.json
catalogs/sources/gtfs/schedule/us-virginia-greensville-emporia-transit-gtfs-463.json
catalogs/sources/gtfs/schedule/us-virginia-grtc-transit-system-gtfs-902.json
catalogs/sources/gtfs/schedule/us-washington-sound-transit-metro-transit-city-of-seattle-king-county-metro-gtfs-267.json
catalogs/sources/gtfs/schedule/usa-ca-relaxsan-gtfs-2030.json

Fix spelling, consistency, and geography errors in US feed metadata

Fix spelling errors

---

scripts/process_csv_in_github_action.swift

Streamlined the code, added more checks and documentation.

Feat major improvements

---

scripts/process_csv_in_github_action.swift

Fixed issue where it outputted every time:
`entity_type=["vp", "tu", "sa"]`
instead of the correct type.

Fix issue with realtime types

---

catalogs/sources/gtfs/schedule/california-arvin-arvin-transit-gtfs-2233.json
catalogs/sources/gtfs/schedule/us-california-arvin-transit-gtfs-2233.json

bug fix: Update california-arvin-arvin-transit-gtfs-2233.json

---

catalogs/sources/gtfs/schedule/us-colorado-golden-gtfs-2413.json
catalogs/sources/gtfs/schedule/us-florida-gainesville-regional-transit-system-gtfs-2412.json
catalogs/sources/gtfs/schedule/us-florida-gainesville-regional-transit-system-gtfs-345.json
catalogs/sources/gtfs/schedule/us-iowa-metropolitan-transit-authority-of-black-hawk-county-gtfs-2414.json
catalogs/sources/gtfs/schedule/us-iowa-metropolitan-transit-authority-of-black-hawk-county-gtfs-575.json
catalogs/sources/gtfs/schedule/us-nevada-jump-around-carson-gtfs-95.json
catalogs/sources/gtfs/schedule/us-new-york-niagara-frontier-transportation-authority-nfta-gtfs-465.json
catalogs/sources/gtfs/schedule/us-virginia-radford-transit-gtfs-2415.json
catalogs/sources/gtfs/schedule/us-virginia-radford-transit-gtfs-380.json

Changes and additions to United States Feeds

US changes

---

catalogs/sources/gtfs/schedule/us-arizona-city-of-sierra-vista-gtfs-145.json
catalogs/sources/gtfs/schedule/us-virginia-fredericksburg-regional-transit-gtfs-1299.json
catalogs/sources/gtfs/schedule/us-virginia-fredericksburg-regional-transit-gtfs-2430.json.json

US Updates

---

catalogs/sources/gtfs/realtime/us-california-alameda-contra-costa-transit-district-ac-transit-gtfs-rt-sa-1400.json
catalogs/sources/gtfs/realtime/us-california-alameda-contra-costa-transit-district-ac-transit-gtfs-rt-tu-1401.json
catalogs/sources/gtfs/realtime/us-california-alameda-contra-costa-transit-district-ac-transit-gtfs-rt-vp-1399.json
catalogs/sources/gtfs/schedule/us-california-alameda-contra-costa-transit-district-ac-transit-gtfs-1244.json
catalogs/sources/gtfs/schedule/us-california-alameda-contra-costa-transit-district-ac-transit-gtfs-2455.json

New authenticated feed for AC transit - using to test our authenticated GTFS schedule feeds workflow to ensure this works correctly before doing a batch update for the 10 other authenticated contributions in the backlog

AC Transit update

---

catalogs/sources/gtfs/schedule/il-ministry-of-transport-and-road-safety-gtfs-2519.json
catalogs/sources/gtfs/schedule/il-unknown-ministry-of-transport-and-road-safety-gtfs-1134.json

Test ssl bug fix: Israel feed

---

catalogs/sources/gtfs/realtime/de-berlin-verkehrsverbund-berlin-brandenburg-gtfs-rt-tu-2378.json
catalogs/sources/gtfs/realtime/es-barcelona-amb-mobilitat-gtfs-rt-sa-2369.json
catalogs/sources/gtfs/realtime/es-barcelona-amb-mobilitat-gtfs-rt-tu-2368.json
catalogs/sources/gtfs/realtime/nl-unknown-ovapi-aggregate-gtfs-rt-sa-1645.json
catalogs/sources/gtfs/realtime/nl-unknown-ovapi-aggregate-gtfs-rt-tu-1644.json
catalogs/sources/gtfs/realtime/nl-unknown-ovapi-aggregate-gtfs-rt-vp-1646.json
catalogs/sources/gtfs/schedule/be-bruxelles-capitale-societe-des-transports-intercommunaux-de-bruxellesmaatschappij-voor-het-intercommunaal-vervoer-te-brussel-stibmivb-gtfs-1088.json
catalogs/sources/gtfs/schedule/be-unknown-stib-mivb-gtfs-1857.json
catalogs/sources/gtfs/schedule/de-bayern-verkehrsverbund-rhein-sieg-gtfs-778.json
catalogs/sources/gtfs/schedule/de-berlin-verkehrsverbund-berlin-brandenburg-gtfs-782.json
catalogs/sources/gtfs/schedule/es-barcelona-autos-castellbisbal-gtfs-892.json
catalogs/sources/gtfs/schedule/es-valencia-emt-valencia-gtfs-795.json
catalogs/sources/gtfs/schedule/fr-paris-ile-de-france-mobilite-gtfs-1026.json
catalogs/sources/gtfs/schedule/it-piemonte-gruppo-torinese-trasporti-gtfs-1142.json
catalogs/sources/gtfs/schedule/nl-unknown-allgo-keolis-gtfs-1077.json
catalogs/sources/gtfs/schedule/us-alabama-birmingham-jefferson-county-transit-authority-gtfs-339.json

Fixes tasks created by @isabelle-dr that are unblocked. 
Including: 
#882 
#880 
#872 
#871 
#869 
#866 
#865 
#864 
#870

Name fixes

---

catalogs/sources/gtfs/realtime/ca-quebec-exo-sorel-varennes-gtfs-rt-sa-1358.json
catalogs/sources/gtfs/realtime/ca-quebec-exo-sorel-varennes-gtfs-rt-tu-1357.json
catalogs/sources/gtfs/realtime/ca-quebec-exo-sorel-varennes-gtfs-rt-vp-1359.json
catalogs/sources/gtfs/realtime/ca-quebec-exo-sud-ouest-gtfs-rt-sa-1355.json
catalogs/sources/gtfs/realtime/ca-quebec-exo-sud-ouest-gtfs-rt-tu-1354.json
catalogs/sources/gtfs/realtime/ca-quebec-transcollines-gtfs-rt-tu-1472.json
catalogs/sources/gtfs/realtime/ca-quebec-transcollines-gtfs-rt-vp-1471.json
catalogs/sources/gtfs/schedule/ca-quebec-exo-chambly-richelieu-carignan-gtfs-750.json
catalogs/sources/gtfs/schedule/ca-quebec-exo-lassomption-gtfs-755.json
catalogs/sources/gtfs/schedule/ca-quebec-exo-laurentides-gtfs-744.json
catalogs/sources/gtfs/schedule/ca-quebec-exo-le-richelain-roussillon-gtfs-2142.json
catalogs/sources/gtfs/schedule/ca-quebec-exo-sorel-varennes-gtfs-741.json
catalogs/sources/gtfs/schedule/ca-quebec-exo-sud-ouest-gtfs-742.json
catalogs/sources/gtfs/schedule/ca-quebec-exo-vallee-du-richelieu-gtfs-752.json
catalogs/sources/gtfs/schedule/ca-quebec-exo-ville-de-sainte-julie-gtfs-753.json
catalogs/sources/gtfs/schedule/ca-quebec-regie-intermunicipale-de-transport-des-collines-gtfs-739.json
catalogs/sources/gtfs/schedule/ca-quebec-reseau-de-transport-de-la-capitale-gtfs-757.json
catalogs/sources/gtfs/schedule/ca-quebec-reseau-de-transport-de-longueuil-gtfs-751.json
catalogs/sources/gtfs/schedule/ca-quebec-rouyn-noranda-gtfs-2603.json
catalogs/sources/gtfs/schedule/ca-quebec-societe-de-transport-de-laval-gtfs-749.json
catalogs/sources/gtfs/schedule/ca-quebec-societe-de-transport-de-levis-gtfs-763.json
catalogs/sources/gtfs/schedule/ca-quebec-societe-de-transport-de-loutaouais-gtfs-740.json
catalogs/sources/gtfs/schedule/ca-quebec-societe-de-transport-de-montreal-stm-gtfs-2126.json
catalogs/sources/gtfs/schedule/ca-quebec-societe-des-transports-de-rimouski-gtfs-2276.json
catalogs/sources/gtfs/schedule/ca-quebec-terrebonne-mascouche-gtfs-754.json

Updates to official status, licenses, and 1 new Quebec feed

Quebec: Canadian Public Transit Database

---

catalogs/sources/gtfs/realtime/us-maine-portland-metro-bus-gtfs-rt-sa-2643.json
catalogs/sources/gtfs/realtime/us-maine-portland-metro-bus-gtfs-rt-tu-2644.json
catalogs/sources/gtfs/realtime/us-maine-portland-metro-bus-gtfs-rt-vp-2645.json
catalogs/sources/gtfs/realtime/us-maine-portland-south-portland-gtfs-rt-sa-2646.json
catalogs/sources/gtfs/realtime/us-maine-south-portland-gtfs-rt-tu-2647.json
catalogs/sources/gtfs/realtime/us-maine-south-portland-gtfs-rt-vp-2647.json
catalogs/sources/gtfs/schedule/it-regione-autonoma-della-sardegna-quadri-orari-traghetti-gtfs-1268.json
catalogs/sources/gtfs/schedule/it-toscana-azienda-trasporti-area-fiorentina-ataf-gtfs-1263.json
catalogs/sources/gtfs/schedule/no-unknown-agder-kollektivtrafikk-as-gtfs-1078.json
catalogs/sources/gtfs/schedule/us-maine-greater-portland-metro-bus-gtfs-2642.json
catalogs/sources/gtfs/schedule/us-maine-greater-portland-metro-bus-gtfs-454.json
catalogs/sources/gtfs/schedule/us-maine-south-portland-gtfs-2641.json
catalogs/sources/gtfs/schedule/us-maine-south-portland-gtfs-453.json
catalogs/sources/gtfs/schedule/us-north-carolina-chapel-hill-transit-cht-gtfs-376.json

Modify Entur feed as requested and update some inactive feeds

Inactive feeds

---

catalogs/sources/gtfs/realtime/us-kentucky-tarc-gtfs-rt-2665.json
catalogs/sources/gtfs/realtime/us-kentucky-tarc-gtfs-rt-sa-2663.json
catalogs/sources/gtfs/realtime/us-kentucky-tarc-gtfs-rt-tu-2664.json
catalogs/sources/gtfs/realtime/us-kentucky-tarc-gtfs-rt-vp-2665.json
catalogs/sources/gtfs/realtime/us-kentucky-transit-authority-of-river-city-tarc-gtfs-rt-sa-1697.json
catalogs/sources/gtfs/realtime/us-kentucky-transit-authority-of-river-city-tarc-gtfs-rt-tu-1696.json
catalogs/sources/gtfs/realtime/us-kentucky-transit-authority-of-river-city-tarc-gtfs-rt-vp-1698.json
catalogs/sources/gtfs/schedule/it-calabria-core-gtfs-2668.json
catalogs/sources/gtfs/schedule/it-lombardia-agenzia-mobilita-ambiente-territorio-gtfs-1231.json
catalogs/sources/gtfs/schedule/it-lombardia-milan-atm-gtfs-2666.json
catalogs/sources/gtfs/schedule/us-california-santa-cruzer-gtfs-2667.json
catalogs/sources/gtfs/schedule/us-kentucky-transit-authority-of-river-city-tarc-gtfs-2662.json
catalogs/sources/gtfs/schedule/us-kentucky-transit-authority-of-river-city-tarc-gtfs-364.json

Adding data from the US and Italy

June feeds

---

catalogs/sources/gtfs/realtime/au-canberra-transport-for-canberra-gtfs-rt-tu-2676.json
catalogs/sources/gtfs/realtime/au-queensland-translink-sunbus-cairns-gtfs-rt-sa-1703.json
catalogs/sources/gtfs/realtime/au-queensland-translink-sunbus-cairns-gtfs-rt-tu-1702.json
catalogs/sources/gtfs/realtime/au-queensland-translink-sunbus-cairns-gtfs-rt-vp-1704.json
catalogs/sources/gtfs/realtime/australia-canberra-transport-canberra-gtfs-rt-sa-2677.json
catalogs/sources/gtfs/realtime/australia-canberra-transport-canberra-gtfs-rt-vp-2677.json
catalogs/sources/gtfs/realtime/australia-canberra-transport-canberra-gtfs-rt-vp-2678.json
catalogs/sources/gtfs/realtime/hu-budapest-bkk-gtfs-rt-sa-2672.json
catalogs/sources/gtfs/realtime/hu-budapest-bkk-gtfs-rt-sa-2673.json
catalogs/sources/gtfs/realtime/hu-budapest-bkk-gtfs-rt-vp-2674.json
catalogs/sources/gtfs/schedule/au-australian-capital-territory-transport-canberra-gtfs-2675.json
catalogs/sources/gtfs/schedule/hu-budapest-budapesti-kozlekedesi-kozpont-bkk-gtfs-990.json

Australia and Hungary additions

June updates: Canberra and Budapest

---

catalogs/sources/gtfs/realtime/au-canberra-transport-for-canberra-gtfs-rt-tu-2676.json
catalogs/sources/gtfs/realtime/australia-canberra-transport-canberra-gtfs-rt-sa-2677.json
catalogs/sources/gtfs/realtime/australia-canberra-transport-canberra-gtfs-rt-vp-2678.json
catalogs/sources/gtfs/schedule/au-australian-capital-territory-transport-canberra-gtfs-2675.json

Add authentication info for Transport for Canberra

Canberra fix

---

catalogs/sources/gtfs/realtime/hu-budapest-bkk-gtfs-rt-sa-2672.json
catalogs/sources/gtfs/realtime/hu-budapest-bkk-gtfs-rt-sa-2673.json
catalogs/sources/gtfs/realtime/hu-budapest-bkk-gtfs-rt-vp-2674.json
catalogs/sources/gtfs/schedule/fr-normandie-hobus-gtfs-2685.zip
catalogs/sources/gtfs/schedule/fr-normandie-hobus-gtfs-836.json
catalogs/sources/gtfs/schedule/pl-pomorskie-pkp-szybka-kolej-miejska-w-trojmiescie-gtfs-1290.json

Adding official tag, deprecating old data

Feed updates

---

catalogs/sources/gtfs/schedule/es-aecfa-gtfs-2727.json
catalogs/sources/gtfs/schedule/es-andalucia-transporte-metropolitano-gtfs-2721.json
catalogs/sources/gtfs/schedule/es-aucorsa-gtfs-2713.json
catalogs/sources/gtfs/schedule/es-autobus-pamplona-gtfs-2719.json
catalogs/sources/gtfs/schedule/es-autobuses-samar-gtfs-2712.json
catalogs/sources/gtfs/schedule/es-bizkaia-bilbobus-gtfs-2681.json
catalogs/sources/gtfs/schedule/es-bizkaia-funicular-de-artxanda-gtfs-2680.json
catalogs/sources/gtfs/schedule/es-bizkaia-metro-bilbao-gtfs-2683.json
catalogs/sources/gtfs/schedule/es-caceres-autobus-urbano-de-caceres-gtfs-2714.json
catalogs/sources/gtfs/schedule/es-euskotren-gtfs-2715.json
catalogs/sources/gtfs/schedule/es-gipuzkoa-dbus-gtfs-2682.json
catalogs/sources/gtfs/schedule/es-guipuzcoa-eibar-gtfs-2735.json
catalogs/sources/gtfs/schedule/es-guipuzcoa-ekialdebus-gtfs-2731.json
catalogs/sources/gtfs/schedule/es-guipuzcoa-goierrialdea-gtfs-2732.json
catalogs/sources/gtfs/schedule/es-guipuzcoa-hernani-hernaniko-hiribusa-gtfs-2734.json
catalogs/sources/gtfs/schedule/es-guipuzcoa-irun-auif-irunbus-gtfs-2724.json
catalogs/sources/gtfs/schedule/es-guipuzcoa-lurraldebus-gtfs-2728.json
catalogs/sources/gtfs/schedule/es-guipuzcoa-lurraldebus-gtfs-2736.json
catalogs/sources/gtfs/schedule/es-guipuzcoa-mondragon-arrasate-gtfs-2733.json
catalogs/sources/gtfs/schedule/es-guipuzcoa-oiartzun-xorrola-gtfs-2725.json
catalogs/sources/gtfs/schedule/es-guipuzcoa-onati-onatiko-herribusa-gtfs-2737.json
catalogs/sources/gtfs/schedule/es-guipuzcoa-tolosaldea-lurraldebus-gtfs-2726.json
catalogs/sources/gtfs/schedule/es-la-union-gtfs-2718.json
catalogs/sources/gtfs/schedule/es-murcia-tdm-gtfs-2729.json
catalogs/sources/gtfs/schedule/es-renfe-feve-gtfs-2717.json
catalogs/sources/gtfs/schedule/es-sevilla-autobuses-urbanos-dos-hermanas-gtfs-2711.json
catalogs/sources/gtfs/schedule/es-tenerife-ferry-fred-olsen-gtfs-2722.json
catalogs/sources/gtfs/schedule/es-tmesa-gtfs-2716.json
catalogs/sources/gtfs/schedule/es-toledo-unauto-gtfs-2723.json
catalogs/sources/gtfs/schedule/es-valladolid-auvasa-gtfs-2730.json

Spain feeds

---

catalogs/sources/gtfs/schedule/au-queensland-bowen-transit-gtfs-675.json
catalogs/sources/gtfs/schedule/au-queensland-north-stradbroke-island-buses-gtfs-652.json
catalogs/sources/gtfs/schedule/au-queensland-trans-north-innisfail-gtfs-673.json
catalogs/sources/gtfs/schedule/au-queensland-translink-brisbane-gtfs-1218.json
catalogs/sources/gtfs/schedule/au-queensland-wide-bay-transit-gtfs-651.json
catalogs/sources/gtfs/schedule/fi-etela-karjala-lappeenranta-gtfs-929.json
catalogs/sources/gtfs/schedule/fi-etela-savo-mikkeli-gtfs-1130.json
catalogs/sources/gtfs/schedule/fi-kanta-hame-tilausliikenne-ali-vehmas-ay-gtfs-1098.json
catalogs/sources/gtfs/schedule/fi-keski-suomi-jyvaskyla-gtfs-867.json
catalogs/sources/gtfs/schedule/fi-kymenlaakso-kymen-charterline-oy-gtfs-1127.json
catalogs/sources/gtfs/schedule/fi-kymenlaakso-tilaustaksit-k-sydanmaanlakka-ky-gtfs-1128.json
catalogs/sources/gtfs/schedule/fi-pohjanmaa-invataksi-niemi-oy-gtfs-1131.json
catalogs/sources/gtfs/schedule/fi-pohjois-karjala-linja-karjala-oy-gtfs-1227.json
catalogs/sources/gtfs/schedule/fi-pohjois-pohjanmaa-oulun-joukkoliikenne-gtfs-869.json
catalogs/sources/gtfs/schedule/fi-satakunta-pori-gtfs-2839.json
catalogs/sources/gtfs/schedule/fr-royan-carabus-gtfs-2842.json
catalogs/sources/gtfs/schedule/it-trentino-alto-adige-trentino-trasporti-esercizio-tte-gtfs-1031.json
catalogs/sources/gtfs/schedule/it-trentino-alto-adige-trentino-trasporti-esercizio-tte-gtfs-2841.json
catalogs/sources/gtfs/schedule/us-connecticut-connecticut-transit-hartford-line-gtfs-2840.json

Australia, Italy, France updates

Australia, Italy, France updates
