MobilityData/mobility-database-catalogs

.github/workflows/verify-source-url.yml
requirements.txt
scripts/verify_source_url.py

**Summary:**
Fixes #4: adds `verify_source_url.py`, `verify-source-url.yml` and `requirements.txt`
Implement
- the script `verify_source_url.py`
- the workflow `verify-source-url.yml`
- the file `requirements.txt`
A PR made with the label `new-gtfs-source` should trigger the workflow, which will pass if the submitted source have an URL different from those on the Mobility Database, fail otherwise.

Fixes #4: adds workflow to verify source stable URL

---

schemas/gtfs_realtime_source_schema.json
schemas/gtfs_schedules_source_schema.json

**Summary:**
Fixes #38: Creating GTFS Realtime JSON schema
This PR adds the GTFS Realtime JSON schema as presented [here](https://docs.google.com/document/d/1Mlz3AXHItInitsOEAKKi8hZV9d3t3gpFbyIZGm67ESU/edit#heading=h.88f252jw0urf). It also updates the title of the GTFS Schedules JSON schema.
Implements:
- `gtfs_realtime_source_schema.json` with one URL per entity type and a static reference field to identify the GTFS Schedules source that the GTFS Realtime source references.
Changes:
- `gtfs_schedules_source_schema.json` title is updates to improve accuracy with the behavior.
A GTFS Realtime source validated against the schema needs at least one of the 3 possible realtime URLs (`realtime_vehicle_positions`, `realtime_trip_updates`, `realtime_alerts`) and can have a …

feat: Adds GTFS Realtime JSON schema

---

.github/workflows/store_latest_datasets_cronjob.yml

**Summary:**
Fixes #68: Cronjob workflow fails.
This PR removes an unnecessary step in `store_latest_dataset_cronjob.yml`  that was causing the workflow to fail on `schedule` events.
Changes:
- `store_latest_dataset_cronjob.yml` is updated to remove the step causing the problem.
The cronjob should run daily without failing.

fix: Cronjob workflow fails

---

requirements.txt
tools/helpers.py
tools/tests/test_helpers.py

**Summary:**
Fixes #76: Automatically replace accents for filename/latest URL
This PR updates the string normalizer function to replace accents automatically.
Changes:
- `helpers.py` to update `normalize()`
The `filename` and latest_url of a source no longer contain accents when the `provider` or `subdivision_name` do.

feat: Automatically replace accents for file names and latest URLs

---

tools/helpers.py
tools/representations.py
tools/tests/test_representations.py

**Summary:**
Fixes #80: Support accents in JSON files
This PR updates every occurrence of `json.dump` and `json.dumps` to add the parameter `ensure_ascii=False`
Changes:
- `helpers.py` and `representations.py` to update `json.dump` and `json.dumps` occurrences.
The JSON files are saved with accents and the representations display them as well.

feat: Support accents in JSON files

---

tools/helpers.py
tools/tests/test_helpers.py

**Summary:**
Fixes #74: Truncating JSON file name (setting limits on provider input)
This PR updates the string normalizer function to truncate the string after the first comma.
Changes:
- `helpers.py` to update `normalize()`
The `filename` and latest_url of a source will be created with only the first part of a given string (eg. provider).

feat: Truncate strings on the first comma to create filename/latest URL

---

catalogs/sources/gtfs/schedule/de-unknown-fluo-grand-est-67-gtfs-1075.json
catalogs/sources/gtfs/schedule/de-unknown-hofmann-omnibusverkehr-gmbh-gtfs-1082.json
catalogs/sources/gtfs/schedule/de-unknown-ulmer-eisenbahnfreunde-gtfs-1081.json
catalogs/sources/gtfs/schedule/es-unknown-consorci-de-transports-de-mallorca-gtfs-1079.json
catalogs/sources/gtfs/schedule/es-unknown-renfe-cercanias-gtfs-1065.json
catalogs/sources/gtfs/schedule/es-unknown-renfe-feve-gtfs-1064.json
catalogs/sources/gtfs/schedule/fr-ile-de-france-transilien-sncf-gtfs-1069.json
catalogs/sources/gtfs/schedule/hu-miskolc-miskolc-varosi-kozlekedesi-mvk-gtfs-1070.json
catalogs/sources/gtfs/schedule/it-lazio-roma-servizi-per-la-mobilita-gtfs-1067.json
catalogs/sources/gtfs/schedule/it-puglia-societa-gestione-multipla-sgm-gtfs-1066.json
catalogs/sources/gtfs/schedule/it-unknown-toremar-toscana-regionale-marittima-gtfs-1068.json
catalogs/sources/gtfs/schedule/nl-unknown-allgo-keolis-gtfs-1077.json
catalogs/sources/gtfs/schedule/no-unknown-agder-kollektivtrafikk-as-gtfs-1078.json
catalogs/sources/gtfs/schedule/nz-bay-of-plenty-baybus-gtfs-1071.json
catalogs/sources/gtfs/schedule/pl-malopolskie-wielicka-komunikacja-wewnatrzgminna-gtfs-1072.json
catalogs/sources/gtfs/schedule/sg-unknown-smrt-gtfs-1076.json
catalogs/sources/gtfs/schedule/tw-changhua-total-passenger-common-total-gtfs-1074.json
catalogs/sources/gtfs/schedule/tw-taichung-fengyuan-passenger-transport-gtfs-1083.json
catalogs/sources/gtfs/schedule/tw-unknown-yuanlin-passenger-transport-general-manager-gtfs-1073.json
catalogs/sources/gtfs/schedule/us-washington-metro-transit-gtfs-1080.json

**Summary:**
Fixes #71: First data import
This PR adds the thirteenth part of first data import for the GTFS Schedule sources in the catalogs.
Changes:
- The GTFS Schedule Sources catalog is extended with 20 new sources.
Same as before but with more sources.

feat: Thirteenth import [SOURCES]

---

.github/workflows/store_latest_datasets_cronjob.yml

**Summary:**
Fixes #108: Cronjob is failing, probably because of a memory error
This PR modifies the `store_latest_dataset_cronjob.yml` workflow so that:
- The dataset artifact is not persisted anymore
- We validate that the dataset is a zip file using python `zipfile` library (not GTFS Kit anymore)
Changes:
- `store_latest_dataset_cronjob.yml` is updated.
The cronjob should run daily without failing.

fix: Modifies cronjob workflow to fix memory error

---

.github/workflows/export_to_csv.yml

**Summary:**
Fixes #28: Add GitHub action to export a CSV
This PR adds a job to the `export_to_csv.yml` workflow to store the CSV in a GCP bucket.
Changes:
- `export_to_csv.yml` to add the job
The CSV is exported as an artifact and updated in the GCP bucket when code or data is merged in main.

feat: Store exported CSV in CGP

---

.github/workflows/export_to_csv.yml

**Summary:**
Fixes #116: Export to CSV workflow fails because of the columns
This PR modifies the `export_to_csv.yml` workflow so that the columns are processed one by one only if they exist in at least one source. Eg. if there is no GTFS Realtime source, then the static_reference column won't be added and no exception will be raised.
Changes:
- `export_to_csv.yml` is updated.
The workflow should run on push to main without failing.

fix: Columns behavior in export_to_csv.yml

---

catalogs/sources/gtfs/schedule/au-new-south-wales-train-replacement-bus-operators-gtfs-1322.json
catalogs/sources/gtfs/schedule/ca-ontario-guelph-transit-gtfs-1300.json
catalogs/sources/gtfs/schedule/fi-pohjois-karjala-posely-gtfs-1317.json
catalogs/sources/gtfs/schedule/fr-ile-de-france-blablacar-bus-gtfs-1314.json
catalogs/sources/gtfs/schedule/fr-ile-de-france-transilien-sncf-gtfs-1299.json
catalogs/sources/gtfs/schedule/gb-unknown-chiltern-railways-gtfs-1311.json
catalogs/sources/gtfs/schedule/it-marche-trenitalia-gtfs-1319.json
catalogs/sources/gtfs/schedule/jp-sizuoka-kakegawa-local-voluntary-operation-bus-gtfs-1303.json
catalogs/sources/gtfs/schedule/jp-sizuoka-omaezaki-local-voluntary-operation-bus-gtfs-1301.json
catalogs/sources/gtfs/schedule/jp-sizuoka-susonohru-gtfs-1302.json
catalogs/sources/gtfs/schedule/nz-christchurch-christchurch-metro-gtfs-1313.json
catalogs/sources/gtfs/schedule/se-unknown-samtrafiken-gtfs-1321.json
catalogs/sources/gtfs/schedule/se-unknown-trafiklab-gtfs-1320.json
catalogs/sources/gtfs/schedule/th-chiang-mai-chiang-mai-university-cmu-gtfs-1310.json
catalogs/sources/gtfs/schedule/th-chiang-mai-kwanwiang-transport-gtfs-1315.json
catalogs/sources/gtfs/schedule/th-chiang-mai-whitebus-gtfs-1325.json
catalogs/sources/gtfs/schedule/tw-changhua-chyuanlin-passenger-transport-general-manager-gtfs-1305.json
catalogs/sources/gtfs/schedule/tw-nantou-nttotal-passenger-common-total-gtfs-1306.json
catalogs/sources/gtfs/schedule/tw-yunlin-ylyuanlin-passenger-transport-general-manager-gtfs-1307.json
catalogs/sources/gtfs/schedule/us-alabama-capital-trailways-gtfs-1308.json
catalogs/sources/gtfs/schedule/us-biscay-la-burundesa-sa-gtfs-1316.json
catalogs/sources/gtfs/schedule/us-california-tri-delta-transit-gtfs-1323.json
catalogs/sources/gtfs/schedule/us-california-turlock-transit-gtfs-1324.json
catalogs/sources/gtfs/schedule/us-massachusetts-massachusetts-ferry-service-gtfs-1309.json
catalogs/sources/gtfs/schedule/us-pennsylvania-beaver-county-transit-authority-gtfs-1312.json
catalogs/sources/gtfs/schedule/us-washington-kitsap-transit-gtfs-1304.json
catalogs/sources/gtfs/schedule/us-wisconsin-milwaukee-county-transit-system-gtfs-1318.json

**Summary:**
Fixes #71: First data import
This PR adds the twentieth part of first data import for the GTFS Schedule sources in the catalogs.
Changes:
- The GTFS Schedule Sources catalog is extended with 27 new sources.
Same as before but with more sources.

feat: Twentieth import [SOURCES]

---

catalogs/sources/gtfs/schedule/ca-alberta-grande-prairie-transit-gtfs-1278.json
catalogs/sources/gtfs/schedule/es-alicante-tram-alicante-gtfs-1039.json
catalogs/sources/gtfs/schedule/us-indiana-muncie-indiana-transit-system-mits-gtfs-719.json

I noticed that these sources have the wrong country code.
The `urls.latest` entries also seem wrong, but I'm not sure if/how they should be fixed.

fix: Fix wrong countries for some sources

---

.github/workflows/export_to_csv.yml

Fixes #180 by adding defining the constant `FEATURES` in `export_to_csv.yml`

fix: Missing constant causes `export_to_csv.yml` to fail

---

schemas/gtfs_realtime_source_schema.json

**Summary:**
Part 2 to #185: Define realtime schema and operations
This PR updates the GTFS Realtime JSON schema so that the `authentication_type` is optional. The previous version made integration tests to fail when a source was missing the `authentication_type`.
Changes:
- `gtfs_realtime_source_schema.json` is updated.
- The user can now add GTFS Realtime sources without specifying the `authentication_type` field.

fix: Updates GTFS Realtime JSON schema to make authentication type optional

---

.github/workflows/direct_download_urls_test_for_sources.yml
tools/helpers.py
tools/representations.py
tools/tests/test_helpers.py
tools/tests/test_representations.py

**Summary:**
Closes #189: Update process to download GTFS Schedule before loading them
This PR implements `download_dataset()` in `tools.helpers` so that we can load the GTFS Schedule dataset in GTFS Kit from a path.
Changes:
- `helpers.py` and `representations.py` are updated to match the new `download_dataset()` function.
- Tests are updated.
- The `direct_download_urls_test_for_sources.yml` workflow is updated to download the dataset first, then load it to assert its readability.
Same as before for the end user.

feat: Refactor process to download GTFS Schedule datasets before loading them

---

.github/workflows/direct_download_urls_test_for_sources.yml
.github/workflows/store_latest_datasets_cronjob.yml

**Summary:**
Closes #197: Daily cron job fails because of a KeyError Exception
This PR fixes `store_latest_dataset_cronjob.yml` and `direct_download_urls_test_for_sources.yml`
The daily cron job and previous PR source check should succeed without a `KeyError` Exception.

fix: Daily cron job fails because of a KeyError Exception

---

.github/workflows/direct_download_urls_test_for_sources.yml

**Summary:**
Closes #204: Fix API secrets issue blocking fork PRs
This PR fixes `direct_download_urls_test_for_sources.yml` so that the API secret is loaded only if a source requiring authentication is added or updated. This change will allow user to contribute data that do not require authentication via forks. Fork PRs with data requiring authentication will still fail. Data requiring authentication must be updated by us via our repo to access the secret.
Users can contribute data that do not require authentication via forks.

fix: Fix API secrets issue blocking fork PRs

---

.github/config.yml
CONTRIBUTING.md
README.md

This PR
- Simplifies README.MD to focus on the most common uses of the repo 
- Expands CONTRIBUTING.MD to include contribution use cases like updating file names, and more information on tests. 
@maximearmstrong It would be helpful to get your perspective on how to write CONTRIBUTING.md so it's easy for a contributor to find the tests and run them on their code changes.

docs: Improvements to README.md and CONTRIBUTING.md

---

catalogs/sources/gtfs/schedule/us-california-flex-v2-developer-test-feed-1-gtfs-1817.json
catalogs/sources/gtfs/schedule/us-california-flex-v2-developer-test-feed-2-gtfs-1818.json
catalogs/sources/gtfs/schedule/us-california-flex-v2-developer-test-feed-3-gtfs-1819.json
catalogs/sources/gtfs/schedule/us-california-fresno-county-rural-transit-agency-fcrta-gtfs-85.json

Add 3 feeds with 'development' status for testing flex-v2 features, representing a variety of service types
- Flex-v2 Developer test feed 1: uses location_groups.txt and locations.geojson includes a "donut" - one service area fully enclosed in another.
- Flex-v2 Developer test feed 2: single service area, with split service times and different booking rules dependent on day
- Flex-v2 Developer test feed 3: On-demand, flexible stop-based service

feat: Add 3 developer test feeds for flex-v2 [SOURCES]

---

.github/workflows/direct_download_urls_test_for_sources.yml

**Summary:**
#216: bug: SSL errors when validating URL
This PR adds a user agent to the GET requests in `direct_download_urls_test_for_sources.yml` so that we fix the SSL and HTTP errors encountered, as suggested [here](https://stackoverflow.com/questions/38489386/python-requests-403-forbidden).
Direct download URLs can be tested without encountering SSL errors related to a missing user agent.

fix: SSL error part 1 - adding user agent to the test workflow

---

catalogs/sources/gtfs/schedule/us-california-bell-gardens-trolley-gtfs-228.json
catalogs/sources/gtfs/schedule/us-california-bellflower-bus-gtfs-227.json
catalogs/sources/gtfs/schedule/us-california-compton-renaissance-gtfs-314.json
catalogs/sources/gtfs/schedule/us-california-downeylink-gtfs-383.json
catalogs/sources/gtfs/schedule/us-california-get-around-town-express-gtfs-606.json
catalogs/sources/gtfs/schedule/us-california-glendora-transportation-division-gtfs-609.json
catalogs/sources/gtfs/schedule/us-california-huntington-park-express-gtfs-558.json
catalogs/sources/gtfs/schedule/us-california-lynwood-trolley-breeze-gtfs-570.json
catalogs/sources/gtfs/schedule/us-california-rosemead-explorer-gtfs-806.json

Update URLs, features (fares-v2), and status (active) for the following LA Regional Feeds:
bellgardens-ca-us
bellflower-ca-us
compton-ca-us
downey-ca-us
getaroundtownexpress-ca-us
glendora-ca-us
huntingtonpark-ca-us
lynwood-ca-us
rosemead-ca-us

Update URLs for LA Regional GTFS [SOURCES]

---

catalogs/sources/gtfs/realtime/unknown-unknown-city-of-seattle-streetcar-gtfs-rt-sa-1547.json
catalogs/sources/gtfs/realtime/unknown-unknown-city-of-seattle-streetcar-gtfs-rt-tu-1548.json
catalogs/sources/gtfs/realtime/unknown-unknown-city-of-seattle-streetcar-gtfs-rt-vp-1546.json
catalogs/sources/gtfs/realtime/us-washington-everett-transit-gtfs-rt-sa-1550.json
catalogs/sources/gtfs/realtime/us-washington-everett-transit-gtfs-rt-tu-1551.json
catalogs/sources/gtfs/realtime/us-washington-everett-transit-gtfs-rt-vp-1549.json
catalogs/sources/gtfs/realtime/us-washington-pierce-transit-gtfs-rt-sa-1544.json
catalogs/sources/gtfs/realtime/us-washington-pierce-transit-gtfs-rt-tu-1543.json
catalogs/sources/gtfs/realtime/us-washington-pierce-transit-gtfs-rt-vp-1545.json
catalogs/sources/gtfs/realtime/us-washington-sound-transit-gtfs-rt-sa-1553.json
catalogs/sources/gtfs/realtime/us-washington-sound-transit-gtfs-rt-tu-1554.json
catalogs/sources/gtfs/realtime/us-washington-sound-transit-gtfs-rt-vp-1552.json
catalogs/sources/gtfs/realtime/us-washington-washington-state-ferries-gtfs-rt-sa-1556.json
catalogs/sources/gtfs/realtime/us-washington-washington-state-ferries-gtfs-rt-tu-1557.json
catalogs/sources/gtfs/realtime/us-washington-washington-state-ferries-gtfs-rt-vp-1555.json

Puget Sound One Bus Away realtime URLs weren't working correctly because they needed to be `https://`. Fixed in this PR.

fix: https url fixes for Puget Sound One Bus Away URLs

---

catalogs/sources/gtfs/schedule/us-arizona-national-park-service-gtfs-1905.json

Grand Canyon National Park South Rim Shuttle feed. Contributed by Eric Englin on behalf of the National Park Service.

grand canyon national park - south rim shuttle [SOURCES]

---

catalogs/sources/gtfs/schedule/pt-lisboa-carris-gtfs-1032.json

The current URL returns an invalid/empty GTFS. The correct URL is `https://gateway.carris.pt/gateway/gtfs/api/v2.8/GTFS`
Thank you!

Updated URL for Carris (Lisboa, PT) [SOURCES]

---

catalogs/sources/gtfs/schedule/fr-hauts-de-france-reseau-de-transport-transpole-de-la-metropole-europeenne-de-lille-gtfs-1201.json

Update Réseau de transport Transpole de la Métropole Européenne de Lille feed so the realtime feed for Lille can match.

Update Réseau de transport Transpole de la Métropole Européenne de Lille [SOURCES]

---

catalogs/sources/gtfs/schedule/pt-braga-transportes-urbanos-de-braga-tub-gtfs-1927.json

This adds the Transportes Urbanos de Braga (TUB) GTFS Schedule feed.
You can check the direct URL to the feed in their website: https://tub.pt/downloads/
Thank you!

feat: Add Transportes Urbanos de Braga (TUB) source [SOURCES]

---

.github/workflows/store_latest_datasets_cronjob.yml

There is a ton of warnings to specify the version and not master. This should fix it.
Ref: https://github.com/MobilityData/mobility-database-catalogs/actions/runs/6175492851
```
google-github-actions/upload-cloud-storage is pinned at "main". We strongly advise against pinning to "@main" as it may be unstable. Please update your GitHub Action YAML from:
uses: 'google-github-actions/upload-cloud-storage@main'
to:
uses: 'google-github-actions/upload-cloud-storage@v0'
Alternatively, you can pin to any git tag or git SHA in the repository.
```

fix: Shut up warnings about upload to cloud action

---

catalogs/sources/gtfs/realtime/us-tennessee-nashville-metropolitan-transit-authority-nashville-mta-gtfs-rt-sa-1621.json
catalogs/sources/gtfs/realtime/us-tennessee-nashville-metropolitan-transit-authority-nashville-mta-gtfs-rt-tu-1620.json
catalogs/sources/gtfs/realtime/us-tennessee-nashville-metropolitan-transit-authority-nashville-mta-gtfs-rt-vp-1622.json
catalogs/sources/gtfs/schedule/us-tennessee-nashville-metropolitan-transit-authority-nashville-mta-gtfs-360.json

Nashville Metro Transit Authority (the legal entity) changed the name of its service to WeGo Public Transit in July of 2018. This meant that the website also changed. While the URLs currently in the database are redirecting with `HTTP 302`, at some point that is likely to stop working. Note that the realtime data feeds did not change.
I have also added the `license` field to the `urls` as it is allowed in the schema. Happy to make other adjustments as needed.

chore: Update Nashville MTA URLs for schedule / realtime [SOURCES]

---

catalogs/sources/gtfs/realtime/us-california-tri-delta-transit-gtfs-rt-sa-1977.json
catalogs/sources/gtfs/realtime/us-california-tri-delta-transit-gtfs-rt-tp-1975.json
catalogs/sources/gtfs/realtime/us-california-tri-delta-transit-gtfs-rt-vp-1976.json
catalogs/sources/gtfs/schedule/ca-ontario-barrie-transit-gtfs-3.json
catalogs/sources/gtfs/schedule/ca-ontario-london-transit-commission-gtfs-2.json
catalogs/sources/gtfs/schedule/us-california-tri-delta-transit-gtfs-1323.json
catalogs/sources/gtfs/schedule/us-california-tri-delta-transit-gtfs-1974.json
catalogs/sources/gtfs/schedule/us-maine-casco-bay-lines-gtfs-1.json
catalogs/sources/gtfs/schedule/us-ohio-athens-public-transit-gtfs-1973.json
catalogs/sources/gtfs/schedule/us-ohio-athens-public-transit-gtfs-4.json

Updates
- Feeds 1-4
- Includes use case examples 
- New GTFS Schedule feed that's authenticated (Tri Delta from 511) 
- Updated GTFS schedule feed that's authenticated (1313 from Metro Christchurch - API key change update not committed.) 
- New GTFS realtime feeds from Tri Delta

Updating feeds [SOURCES]

---

.github/workflows/add_new_or_updated_feeds.yml
scripts/process_csv_in_github_action.swift

* Removed empty parameters from Python function calls (ex. provider="").
* Added `[SOURCES]` to branch name
* statuses as lowercase
* `entity_type` provided as an array.
* Added note about not trying to fix """" from the script's output as this will cause an error when executed in the Python script.

Fixes at Emma's request

---

.github/workflows/direct_download_urls_test_for_sources.yml
.github/workflows/integration_tests.yml
.github/workflows/python_style_checker.yml
.github/workflows/unit_tests.yml

In order to prevent triggering these workflows every time a change is made to another workflow or a script inside the `scripts/` folder, added paths-ignore.

Added paths-ignore

---

CONTRIBUTING.md
schemas/gtfs_schedule_source_schema.json
tools/constants.py
tools/operations.py
tools/representations.py
tools/tests/test_operations.py

Closes #319 
Closes #318 
✅ Added `redirects` to python `add` operation for schedule feeds
✅ Added `redirects` to python `update` operation for schedule feeds
✅ Added `feed_contact_email` to python `add` operation for schedule feeds
✅ Added `feed_contact_email` to python `update` operation for schedule feeds
✅ Updated unit tests
✅ Updated code snippet in documentation

feat: added redirects and feed contact email to operations

---

tools/representations.py
tools/tests/test_operations.py

Introduces fixes to #319:
- `None` is now supported for `redirects` -- the result will be an empty array
- Tests are fixed -- they set an numerical id for the redirect instead of a string

fix: redirect field fixes

---

scripts/process_csv_in_github_action.swift

Request from Emma: 
> can we make it so if a row entry has a data type of "source update", not to overwrite the license field with INVALID_OR_NO_URL_PROVIDED?

Fix: removed `license_url` from update feed requests

---

.github/workflows/add_new_or_updated_feeds.yml

Removed the channel IDs as this was deemed irrelevant since the webhook only works with one specific channel.

Removed channel IDs in payload for Slack notif

---

.github/workflows/add_new_or_updated_feeds.yml

Apparently the new payload failed, reverted back to the previous payload with some improvements.

Reverted syntax to previous one that worked, with updates

---

catalogs/sources/gtfs/schedule/fr-bretagne-societe-deconomie-mixte-des-transports-de-lagglomeration-nantaise-tan-gtfs-1025.json
catalogs/sources/gtfs/schedule/fr-pays-de-la-loire-naolib-gtfs-1025.json

This PR contains:
- Update provider name
- Fix subdivision name (Nantes is no longer in 'Bretagne' since half a century)
Should we also change json file name and lastest url ? However I guess that it might break data anteriority.

fix: update Nantes feed

---

catalogs/sources/gtfs/realtime/us-iowa-des-moines-dart-gtfs-rt-sa-1769.json
catalogs/sources/gtfs/realtime/us-iowa-des-moines-dart-gtfs-rt-tu-1770.json
catalogs/sources/gtfs/realtime/us-iowa-des-moines-dart-gtfs-rt-vp-1771.json

3 realtime feeds were associated with the wrong static feed and had the wrong provider name. Updating thanks to a contributor.

fix: Des Moines Fix

---

.github/workflows/add_new_or_updated_feeds.yml
.github/workflows/export_to_csv.yml

This PR solves this issue in the mobility-feed-api repo: [#407](https://github.com/MobilityData/mobility-feed-api/issues/407)
There was a desynchronization of the catalog csv file used in the integration tests and the contents of the DB in the QA repo.
Now modified so the catalog-sources-updated trigger is sent to the mobility-feed-api repo each time the source.csv file is generated, ie after a PR changing the catalog is merged.
Testing for this is tricky. I want to test mostly the notification mechanism. But I don't want to trigger all the GH actions that have catalog-sources-updated as a trigger. Because this will update the DBs in DEV, QA and PROD.
I could create a dummy GH action in mobility-feed-api that would just receive a test trigger and print something. But this action needs to …

Changed when the catalog-sources-updated trigger is sent

---

scripts/export_to_csv.py

This PR solves this issue in the mobility-feed-api repo: [#407](https://github.com/MobilityData/mobility-feed-api/issues/407)
There was already a PR #362 , but it did not solve all the problems.
This time some of the provider fields in the json files of the catalog had spaces at the end.
This was put in sources.csv.
But when filling the DB the spaces were removed.
This created a discrepancy between sources.csv and the DB that caused the integration tests to fail.
Corrected the problem by removing extraneous spaces on every string read from the json files, before writing to sources.csv.
Here is the list of entries that were modified:
405, 902, 1112, 1115, 1124, 1132, 1134, 1204, 1214, 1215, 1216, 1217, 1218, 1229, 1312, 1321, 1476, 1477, 1478, 1619, 1636, 2020

Stripped spaces when creating sources.csv

---

.github/workflows/export_to_csv.yml
.github/workflows/store_latest_datasets_cronjob.yml

As I was testing https://github.com/MobilityData/mobility-database-catalogs/pull/365 I realized that there was no way to trigger the upload of sources.csv to GCP apart from changing the json files in the catalog.
This PR optionally allows upload when the trigger is manual.
It also corrects some problem with using old versions of GH actions.

Allow csv upload when triggered by hand

---

catalogs/sources/gtfs/schedule/us-north-carolina-wave-transit-gtfs-1110.json
catalogs/sources/gtfs/schedule/us-north-carolina-wave-transit-gtfs-1861.json
catalogs/sources/gtfs/schedule/us-north-carolina-wave-transit-gtfs-1862.json
catalogs/sources/gtfs/schedule/us-north-carolina-wave-transit-gtfs-2026.json

Includes the following contributions from Wave Transit: 
- A new feed for the UNCW Seahawk Shuttle
- Updating the pre-existing https://www.wavetransit.com/gtransit/google_transit.zip feed's status to "active"
- Updating the old URLs as deprecated

Wave Transit's updated feeds [SOURCES]

---

scripts/process_csv_in_github_action.swift

Converted Realtime code to an array

---

catalogs/sources/gtfs/schedule/pl-kujawsko-pomorskie-miejski-zaklad-komunikacji-w-toruniu-mzk-torun-gtfs-2089.json
catalogs/sources/gtfs/schedule/pl-mazowieckie-komunikacja-miejska-lomianki-gtfs-1123.json
catalogs/sources/gtfs/schedule/pl-mazowieckie-mzdik-radom-gtfs-1015.json
catalogs/sources/gtfs/schedule/pl-mazowieckie-mzdik-radom-gtfs-2090.json
catalogs/sources/gtfs/schedule/pl-mazowieckie-warszawska-kolej-dojazdowa-wkd-gtfs-2091.json
catalogs/sources/gtfs/schedule/pl-mazowieckie-warszawska-kolej-dojazdowa-wkd-gtfs-863.json
catalogs/sources/gtfs/schedule/pl-mazowieckie-warszawski-transport-publiczny-ztm-warszawa-gtfs-1008.json
catalogs/sources/gtfs/schedule/pl-mazowieckie-warszawski-transport-publiczny-ztm-warszawa-gtfs-2092.json
catalogs/sources/gtfs/schedule/pl-pomorskie-miejski-zaklad-komunikacji-w-wejherowie-mzk-wejherowo-gtfs-2084.json
catalogs/sources/gtfs/schedule/pl-pomorskie-zarzad-drog-i-zieleni-gdynia-zkm-gdynia-gtfs-2094.json
catalogs/sources/gtfs/schedule/pl-pomorskie-zarzad-transportu-miejskiego-gdansk-ztm-gdansk-gtfs-1014.json
catalogs/sources/gtfs/schedule/pl-pomorskie-zarzad-transportu-miejskiego-gdansk-ztm-gdansk-gtfs-2093.json
catalogs/sources/gtfs/schedule/pl-unknown-polregio-gtfs-2087.json
catalogs/sources/gtfs/schedule/pl-unknown-polskie-koleje-panstwowe-intercity-pkp-intercity-gtfs-2088.json
catalogs/sources/gtfs/schedule/pl-warminsko-mazurskie-miejski-zaklad-komunikacji-w-elku-mzk-elk-gtfs-2086.json
catalogs/sources/gtfs/schedule/pl-zachodniopomorskie-komunikacja-autobusowa-swinoujscie-ka-swinoujscie-gtfs-2085.json

As mostly stated in the commit messages:
feat: add more feeds from mkuran.pl [SOURCES] (the only available one which I haven't added is the Kielce one, as they have a funky license (see mkuran.pl/gtfs).)
- pl-kujawsko-pomorskie-miejski-zaklad-komunikacji-w-toruniu-mzk-torun-gtfs-2083.json
- pl-pomorskie-miejski-zaklad-komunikacji-w-wejherowie-mzk-wejherowo-gtfs-2084
- pl-zachodniopomorskie-komunikacja-autobusowa-swinoujscie-ka-swinoujscie-gtfs-2085.json
- pl-warminsko-mazurskie-miejski-zaklad-komunikacji-w-elku-mzk-elk-gtfs-2086
- pl-unknown-polregio-gtfs-2087
- pl-unknown-polskie-koleje-panstwowe-intercity-pkp-intercity-gtfs-2088
fix: update URLs for feeds from mkuran.pl [SOURCES] (`/feed/*` -> `/gtfs/*`)
- pl-mazowieckie-warszawska-kolej-dojazdowa-wkd-gtfs-863.json
- …

Poland mkuran.pl updates [SOURCES]

---

catalogs/sources/gtfs/schedule/tr-kocaeli-eshot-gtfs-1823.json
catalogs/sources/gtfs/schedule/tr-kocaeli-izban-gtfs-1828.json
catalogs/sources/gtfs/schedule/tr-kocaeli-metro-izmir-gtfs-1824.json
catalogs/sources/gtfs/schedule/tr-kocaeli-tram-izmir-gtfs-1829.json

fix: Fixed incorrect locations of feeds that were previously mislabeled as Turkey, Kocaeli, Izmit. The feeds are actually for Turkey, Izmir.  (Also fixing [this](https://github.com/MobilityData/mobility-database-catalogs/pull/495) pr)
- tr-kocaeli-metro-izmir-gtfs-1824.json
- tr-kocaeli-eshot-gtfs-1823.json
- tr-kocaeli-izban-gtfs-1828.json
- tr-kocaeli-tram-izmir-gtfs-1829.json
I am not sure if the files need to be renamed as well.

Fix mislabeling of feeds from Turkey, Kocaeli, Izmit to Turkey, Izmir

---

.github/workflows/direct_download_urls_test_for_sources.yml
.github/workflows/export_to_csv.yml
.github/workflows/integration_tests.yml
.github/workflows/store_latest_datasets_cronjob.yml
.github/workflows/unit_tests.yml

Upgrade upload artifact action to the latest version as older versions are [deprecated](https://github.com/actions/upload-artifact)
Example of failing action, [link](https://github.com/MobilityData/mobility-database-catalogs/actions/runs/11241281397)

fix: upgrade upload artifact action to v4

---

.github/workflows/export_to_csv.yml

Download artifact action has been deprecated. This PR upgrades the action to v4, its latest version.

fix: download-artifact action

---

catalogs/sources/gtfs/schedule/be-wallonne-tec-gtfs-1868.json
catalogs/sources/gtfs/schedule/ca-ontario-york-region-transit-gtfs-728.json

As per [schema definition](https://github.com/MobilityData/mobility-database-catalogs/blob/36ed76887c00842937ba0acdfdf586765b0a3046/schemas/gtfs_schedule_source_schema.json#L145), the license URL field is named `license` instead of `license_url.` This PR fix the field name in two occurrences.

fix: rename invalid license field

---

README.md

Currently broken / outdated - get_sources_by_status takes status as param not feature.

README: Fix example for get_sources_by_status, takes status as arg

---

README.md

The `https://bit.ly/catalogs-csv` link is deprecated. Replaced it with `https://share.mobilitydata.org/catalogs-csv`
Both are redirected to `https://storage.googleapis.com/storage/v1/b/mdb-csv/o/sources.csv?alt=media`, so there should be no change for the user.

Changed the sources.csv bit.ly link to share.mobilitydata.org

---

catalogs/sources/gtfs/schedule/ch-unknown-swiss-federal-railways-sbb-gtfs-2144.json
catalogs/sources/gtfs/schedule/de-unknown-postauto-ag-gtfs-2053.json

opentransportdata.swiss has publicly shared that their permalinks are changing. This update includes those domain changes so the URLs don't break in February.

[feed update]  opentransportdata.swiss domain change

---

tools/constants.py
tools/helpers.py
tools/tests/test_helpers.py

- Implemented fallback mechanism with browser-like headers for 403 errors
- Added HTTPError to imports from requests.exceptions
- Added urlparse for URL parsing in fallback logic
- Included test cases for 403 fallback success and failure scenarios

bug: Add 403 error fallback handler for dataset downloads

---

scripts/export_to_csv.py

Closes #765 
An `is_official` flag was added in https://github.com/MobilityData/mobility-database-catalogs/pull/649
This PR puts this flag in the sources.csv in a an `is_official` column.
Note: I placed the column right after the `provider` column instead of at the end. 
I thought these columns go together, but it may be that some people using the csv file rely on the position of the columns (i.e. not placing `is_official` at the end is not backwards compatible).

feat: Added is_official to the generated sources.csv
